// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.0
// source: monitor.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoinMixerMonitor_UTXODeposit_FullMethodName = "/pb.CoinMixerMonitor/UTXODeposit"
)

// CoinMixerMonitorClient is the client API for CoinMixerMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoinMixerMonitorClient interface {
	// 监听转账区消息
	UTXODeposit(ctx context.Context, in *UTXODepositRequest, opts ...grpc.CallOption) (*Empty, error)
}

type coinMixerMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewCoinMixerMonitorClient(cc grpc.ClientConnInterface) CoinMixerMonitorClient {
	return &coinMixerMonitorClient{cc}
}

func (c *coinMixerMonitorClient) UTXODeposit(ctx context.Context, in *UTXODepositRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CoinMixerMonitor_UTXODeposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoinMixerMonitorServer is the server API for CoinMixerMonitor service.
// All implementations must embed UnimplementedCoinMixerMonitorServer
// for forward compatibility.
type CoinMixerMonitorServer interface {
	// 监听转账区消息
	UTXODeposit(context.Context, *UTXODepositRequest) (*Empty, error)
	mustEmbedUnimplementedCoinMixerMonitorServer()
}

// UnimplementedCoinMixerMonitorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoinMixerMonitorServer struct{}

func (UnimplementedCoinMixerMonitorServer) UTXODeposit(context.Context, *UTXODepositRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UTXODeposit not implemented")
}
func (UnimplementedCoinMixerMonitorServer) mustEmbedUnimplementedCoinMixerMonitorServer() {}
func (UnimplementedCoinMixerMonitorServer) testEmbeddedByValue()                          {}

// UnsafeCoinMixerMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoinMixerMonitorServer will
// result in compilation errors.
type UnsafeCoinMixerMonitorServer interface {
	mustEmbedUnimplementedCoinMixerMonitorServer()
}

func RegisterCoinMixerMonitorServer(s grpc.ServiceRegistrar, srv CoinMixerMonitorServer) {
	// If the following call pancis, it indicates UnimplementedCoinMixerMonitorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoinMixerMonitor_ServiceDesc, srv)
}

func _CoinMixerMonitor_UTXODeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UTXODepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinMixerMonitorServer).UTXODeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoinMixerMonitor_UTXODeposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinMixerMonitorServer).UTXODeposit(ctx, req.(*UTXODepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoinMixerMonitor_ServiceDesc is the grpc.ServiceDesc for CoinMixerMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoinMixerMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CoinMixerMonitor",
	HandlerType: (*CoinMixerMonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UTXODeposit",
			Handler:    _CoinMixerMonitor_UTXODeposit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitor.proto",
}
